
-- Run this in your Supabase SQL Editor

-- 1. Table for Game Scores
create table if not exists scores (
  id bigint generated by default as identity primary key,
  user_name text not null,
  score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table for Resolutions
create table if not exists resolutions (
  id bigint generated by default as identity primary key,
  user_name text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Table for Advice Tracking (Optional history)
create table if not exists advice (
  id bigint generated by default as identity primary key,
  user_name text not null,
  advice_text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) is good practice, 
-- but for this public demo we might want to allow all inserts:
alter table scores enable row level security;
alter table resolutions enable row level security;
alter table advice enable row level security;

-- Policy: Allow ANYONE to select/insert (Public Wall style)
-- WARNING: This allows anyone to edit/delete if not careful, 
-- but simple SELECT/INSERT policies are safer.

create policy "Public Select Scores" on scores for select using (true);
create policy "Public Insert Scores" on scores for insert with check (true);

create policy "Public Select Resolutions" on resolutions for select using (true);
create policy "Public Insert Resolutions" on resolutions for insert with check (true);
-- Note: Realistically you might want to only allow deleting your own, 
-- but without Auth, we can't verify identity securely. 
-- We will allow deleting rows WHERE user_name matches current session name (in frontend logic, insecure but functional).
create policy "Public Delete Resolutions" on resolutions for delete using (true);

create policy "Public Select Advice" on advice for select using (true);
create policy "Public Insert Advice" on advice for insert with check (true);
