
-- Run this in your Supabase SQL Editor

-- 1. Table for Game Scores
create table if not exists scores (
  id bigint generated by default as identity primary key,
  user_name text not null,
  score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FIX: If table exists but missing columns (run this to fix)
alter table scores add column if not exists user_name text default 'Anonymous';
alter table scores add column if not exists created_at timestamp with time zone default timezone('utc'::text, now()) not null;

-- 2. Table for Resolutions
create table if not exists resolutions (
  id bigint generated by default as identity primary key,
  user_name text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Table for Advice Tracking (Optional history)
create table if not exists advice (
  id bigint generated by default as identity primary key,
  user_name text not null,
  advice_text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) is good practice, 
-- but for this public demo we might want to allow all inserts:
alter table scores enable row level security;
alter table resolutions enable row level security;
alter table advice enable row level security;

-- Policy: Allow ANYONE to select/insert (Public Wall style)
-- WARNING: This allows anyone to edit/delete if not careful, 
-- but simple SELECT/INSERT policies are safer.

-- Policy: Allow ANYONE to select/insert (Public Wall style)
-- FIX: Drop policies if they exist to allow re-running script without errors
drop policy if exists "Public Select Scores" on scores;
drop policy if exists "Public Insert Scores" on scores;
create policy "Public Select Scores" on scores for select using (true);
create policy "Public Insert Scores" on scores for insert with check (true);

drop policy if exists "Public Select Resolutions" on resolutions;
drop policy if exists "Public Insert Resolutions" on resolutions;
drop policy if exists "Public Delete Resolutions" on resolutions;
create policy "Public Select Resolutions" on resolutions for select using (true);
create policy "Public Insert Resolutions" on resolutions for insert with check (true);
create policy "Public Delete Resolutions" on resolutions for delete using (true);

drop policy if exists "Public Select Advice" on advice;
drop policy if exists "Public Insert Advice" on advice;
create policy "Public Select Advice" on advice for select using (true);
create policy "Public Insert Advice" on advice for insert with check (true);

-- 4. Table for Users (Registration)
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

drop policy if exists "Public Select Users" on users;
drop policy if exists "Public Insert Users" on users;
create policy "Public Select Users" on users for select using (true);
create policy "Public Insert Users" on users for insert with check (true);

-- DATA RESET (Uncomment to clear data)
-- truncate table scores;
-- truncate table resolutions;
-- truncate table advice;
-- truncate table users;

-- CLEANUP: specific (Run to remove Anonymous test data)
delete from scores where user_name = 'Anonymous';
delete from resolutions where user_name = 'Anonymous';
delete from advice where user_name = 'Anonymous';
delete from users where name = 'Anonymous';

